### PR TITLE
[Core]: Improved lost CF pruning

### LINKED ISSUE #192: Interfering internal CF addresses
**Describe the bug**
When creating two internal CF addresses with the same preferred address, they will both continue using the same address. This causes information for one devices to be handled by both and leading to undefined behavior. This bug occurred by running two executables, though it might also happen within the same executable?

**How to replicate**
Run the VT "auxiliary function" and "version3 object pool" examples simultaneously, with both of them preferring the same internal address.

### PR DESCRIPTION
**Pull request by ad3154**
* Added active control function pruning so that if a control function fails to claim after a request for the address claim PGN, we move that control function to the inactive list and invalidate its address. 

This was always meant to be a part of how we manage address claiming, but for whatever reason got left behind. This greatly increases the reliability of checking a control function's address being valid.

* Fixed a random crash in unit tests.
* Added additional logging to the address claim state machine to more clearly describe what is happening.

Closes #192

### CODE REVIEW

**Comment by ad3154** [comment]
@GwnDaan Since this is linked to your issue originally, when you have time, I'd love a review

**Comment by GwnDaan** [comment]
> @GwnDaan Since this is linked to your issue originally, when you have time, I'd love a review

Sounds good, it will still be a few days before I can do any testing or reviewing. But I'll be happy to test it when I get the time :)

**Comment by GwnDaan** [comment]
Hi @ad3154, still seeing some weird behavior when trying to steal a CF:

To replicate, first start the version3_object_pool example (claims 0x1C):
image

Then start the aux_inputs example (modified to claim 0x1C as well):
image

But now the version3_object_pool example loses connection with the VT:
image

What are your thoughts?

**Comment by GwnDaan** [comment]
The other way around fails now as well (at the time of creating #192 it worked fine IIRC):

Here I first started the` aux_input` example and then the `version3_object_pool` example:
image

image

File: isobus/src/can_address_claim_state_machine.cpp [hunk 1]
```diff
@@ -170,6 +170,10 @@ namespace isobus
 				{
 					if (send_address_claim(m_preferredAddress))
 					{
+						CANStackLogger::debug("[AC]: Internal control function %016llx has claimed address %u on channel %u",
+						                      m_isoname.get_full_name(),
+						                      m_portIndex,
+						                      m_preferredAddress);
```
Comment (GwnDaan) [inline isobus/src/can_address_claim_state_machine.cpp:176]:
```suggestion
						CANStackLogger::debug("[AC]: Internal control function %016llx has claimed address %u on channel %u",
						                      m_isoname.get_full_name(),
						                      m_preferredAddress,
						                      m_portIndex);
```

File: isobus/src/can_address_claim_state_machine.cpp [hunk 2]
```diff
@@ -189,13 +193,20 @@ namespace isobus
 						if ((nullptr == CANNetworkManager::CANNetwork.get_control_function(m_portIndex, i, {})) && (send_address_claim(i)))
 						{
 							addressFound = true;
+							CANStackLogger::debug("[AC]: Internal control function %016llx could not use the preferred address, but has claimed address %u on channel %u",
+							                      m_isoname.get_full_name(),
+							                      m_portIndex,
+							                      m_preferredAddress);
```
Comment (GwnDaan) [inline isobus/src/can_address_claim_state_machine.cpp:199]:
```suggestion
							CANStackLogger::debug("[AC]: Internal control function %016llx could not use the preferred address, but has claimed address %u on channel %u",
							                      m_isoname.get_full_name(),
							                      m_preferredAddress,
							                      m_portIndex);
```

**Review by GwnDaan — CHANGES_REQUESTED** [review]

**Comment by ad3154** [comment]
Thanks for the feedback! I will continue working on this...

**Comment by ad3154** [comment]
I think I've got all the issues worked out in here now.

In the following log output, you can see the VT example runs normally, and properly detects when I unplug a device from the bus.

image

**Comment by ad3154** [comment]
Okay, now the unit test should be fixed as well. 🙂

**Comment by GwnDaan** [comment]
> The other way around fails now as well (at the time of creating #192 it worked fine IIRC):
> 
> Here I first started the` aux_input` example and then the `version3_object_pool` example: image
> 
> image

I still partially have this issue. It seems that when the aux_inputs example get's kicked of it's preferred address, it just claims it's preferred address back again according to the logs:

`aux_inputs` example (started before `version3_object_pool`  example):
image

`version3_object_pool` example logs (started right after the still running `aux_inputs` example):
image

**Comment by ad3154** [comment]
Yeah, that's not the right behavior - I'll take a look at that, thanks

**Comment by ad3154** [comment]
Looks like a logging issue... I was passing in the preferred address to that log statement instead of the loop variable.
image

**Comment by GwnDaan** [comment]
Hmm then the issue with the object pool might be out of the scope of this PR? Not sure if it's related to CF's

> `version3_object_pool` example logs (started right after the still running `aux_inputs` example):
> image

**Comment by ad3154** [comment]
After recreating it and looking at a candump, it seems like the address claiming messages and process are correct, but looking at the address table in the network manager, there's definitely something sketchy going on, as the slot that should be the Vt Example's ICF is occupied by the external control function that moved to a different address. So although the correct messages were sent, our internal tracking of them seems to be confused. I've come this far with it, I might as well try and fix it before merging this in... 
image

**Comment by ad3154** [comment]
Okay, now I think I've got it. Ready for re-review @GwnDaan 

image

**Review by GwnDaan — APPROVED** [review]
