### PR TITLE
[CI]: Automated build for testing no threads

### LINKED ISSUE #632: CAN_STACK_DISABLE_THREADS is not checked in all occasions
**Describe the bug**
There are a few places that uses std::mutex, std::thread, etc. without checking the disable macro first

**Supporting Documentation**
- in some cases it is probably just changing std::lock_guard to the internal macro (`LOCK_GUARD(Mutex, managedWorkingSetMutex);`) like [here](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/blob/3b5dd50fc3e08bc1bdcff3191f164c82e684d100/isobus/src/isobus_virtual_terminal_working_set_base.cpp#L2950)
- but for example [here](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/blob/3b5dd50fc3e08bc1bdcff3191f164c82e684d100/isobus/src/isobus_virtual_terminal_server_managed_working_set.cpp#L41) I'am not sure if there is an easy fix possible or if a greater effort is needed, to remove the usage of std::thread

**Environment:**

- all envs, but it leads to compile errors especially on platforms that don't have thread support e.g. gcc arm none eabi

### PR DESCRIPTION
**Pull request by GwnDaan**
## Describe your changes
See #638, this PR continues the work with adding a Github Actions build to verify all code in the future build fine with disabled threading.

Fixes #632

### CODE REVIEW

File: isobus/src/isobus_virtual_terminal_objects.cpp [hunk 1]
```diff
@@ -3226,20 +3225,6 @@ namespace isobus
...
-		{
-			auto child = get_object_by_id(get_variable_reference(), parentWorkingSet->get_object_tree());
-
-			if ((nullptr != child) && (isobus::VirtualTerminalObjectType::StringVariable == child->get_object_type()))
-			{
-				return std::static_pointer_cast<isobus::StringVariable>(child)->get_value();
-			}
-		}
-		return get_value();
-	}
```
Comment (GwnDaan) [inline isobus/src/isobus_virtual_terminal_objects.cpp]: @martonmiklos we have to remove this function in order to keep using the `isobus_virtual_terminal_objects.hpp` in the VT client code. Are you fine with changing the VirtualTerminal GUI project to make it do the logic itself?

Comment (VzdornovNA88) [reply isobus/src/isobus_virtual_terminal_objects.cpp]: I apologize for interfering in the conversation, I looked at this method, well... it doesn't seem to work for VT, If you look closely at the implementations of other objects in this file, you can see that many of them also use this logic with a 'referenced value', it's just that the working set was needed only here and cutting off the 'displayed_value' just because we have a CAN_STACK_DISABLE_THREADS knife would not be a very correct solution in my opinion, and although I don't really agree that this method should be called that way (I still see it as a get_value overload for example) it would surprise me to see this logic in VT. If so much code hadn't been done for 'referenced values', I would have preferred a different way to get them - something like OutputStringRefferenced = make_ref_value_from<OutputString>(workingSetPtr ) - this interface could be located in another file that depends on the runtime of the working set but now that a lot has already been done... nevertheless, porting this code to VT looks strange, it's better to follow a more conservative path in my opinion.

File: CMakeLists.txt [hunk 2]
```diff
@@ -33,6 +34,16 @@ option(
...
   OFF)
+
+# Disable threads if the header is not available
+check_include_file_cxx(thread HAS_STD_THREAD_HEADER)
+if(NOT HAS_STD_THREAD_HEADER)
+  message(
+    WARNING
+      "C++ <thread> header not found. Disabling CAN_STACK_DISABLE_THREADS.")
+  set(CAN_STACK_DISABLE_THREADS ON)
+endif()
```
[the remark this answers is not in the document]
Comment (VzdornovNA88) [reply CMakeLists.txt]: of course, it's a strange case when a user disables it, but he doesn't have the source code, I agree. This is just a formal nuance, I consider all combinations to be test cases.

**Review by ad3154 — APPROVED** [review]
